services:
    PoP\UserState\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\UserState\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true

    PoP\UserState\Hooks\:
        resource: '../src/Hooks/*'
        public: true
