services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\UserState\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\UserState\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true

    PoP\UserState\Conditional\CacheControl\TypeResolverDecorators\:
        resource: '../src/Conditional/CacheControl/TypeResolverDecorators/*'
        public: true

    PoP\UserState\Hooks\:
        resource: '../src/Hooks/*'
        public: true
